//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Пр4_Агентсво_недвижимостиEntities : DbContext
    {
        public Пр4_Агентсво_недвижимостиEntities()
            : base("name=Пр4_Агентсво_недвижимостиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dolzhnost> dolzhnost { get; set; }
        public virtual DbSet<pol> pol { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tip_zhilya> tip_zhilya { get; set; }
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Допольнительние_услуги> Допольнительние_услуги { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Недвижимость> Недвижимость { get; set; }
        public virtual DbSet<Отчетности> Отчетности { get; set; }
        public virtual DbSet<Собственник> Собственник { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Услуга> Услуга { get; set; }
    }
}
