//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договор
    {
        public int Id_Договор { get; set; }
        public Nullable<int> Id_Сотрудник { get; set; }
        public Nullable<int> Id_Клиент { get; set; }
        public Nullable<int> Id_Услуга { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Услуга Услуга { get; set; }
    }
}
