//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        public int Id_Заявка { get; set; }
        public int Id_Клиент { get; set; }
        public int Id_Услуга { get; set; }
        public int Id_Недвижемость { get; set; }
        public int Id_Сотрудник { get; set; }
        public System.DateTime Дата_заявки { get; set; }
        public string Статус { get; set; }
        public Nullable<int> Id_Доп__Услуги { get; set; }
    
        public virtual Допольнительние_услуги Допольнительние_услуги { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Недвижимость Недвижимость { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Услуга Услуга { get; set; }
    }
}
