//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчетности
    {
        public int Id_Отчетности { get; set; }
        public Nullable<int> Id_Сотрудник { get; set; }
        public Nullable<System.DateTime> Период_отчетности { get; set; }
        public string Общий_доход { get; set; }
        public string Налоговые_вычети { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
